version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: learnbetterauth
    environment:
      - NODE_ENV=production
    expose:
      - "3000"
    restart: unless-stopped

  nginx:
    image: nginx:1.27-alpine
    container_name: learnbetterauth-nginx
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      # Mount your Let's Encrypt certs (ensure the host path exists on the server)
      - /etc/letsencrypt:/etc/letsencrypt:ro
    restart: unless-stopped
